### ISSUE TITLE
Webpack build dumps image and fonts into root dir

### ISSUE THREAD

**Issue by FKolwa** [redhatcloudx/cloud-image-directory-frontend#60]
For some reason webpack dumps all images and fonts into the root dir after performing a productionbuild.
The resources are still available in their respective subdir (fonts / images) and the duplicated files can be removed without issue but this is still annoying and pollutes our S3 bucket if we don't manually remove them.

How to replicate:
run "npm run build" from within project dir
look into dist folder

**Comment by schogges** [comment]
Hi @FKolwa :)
Would it be possible that I work on it?

**Comment by FKolwa** [comment]
Hey @schogges , of course! Feel free to take the issue and thanks for your contribution ;)
