### ISSUE TITLE
Pagination works oddly when going to the previous page from the last page

### ISSUE THREAD

**Issue by ondrejbudai** [redhatcloudx/cloud-image-directory-frontend#67]
Reproducer:
- Go to the last page
- Go to previous pages

After several steps to previous pages, the top 6 images no longer change.

**Comment by FKolwa** [comment]
I managed to reproduce this behavior on Azure. If you continue clicking the images shown suddenly start to change again. @poncovka I have a feeling that this is the symptom of the duplicate image problem you have identified on the transformer.

**Comment by FKolwa** [comment]
Solved in redesign. More specific #117
