### ISSUE TITLE
No other options for pagination than 50 per page

### ISSUE THREAD

**Issue by ondrejbudai** [redhatcloudx/cloud-image-directory-frontend#68]
The button is currently quite useless, there's just one option: 50 items per a page:

![a screenshot showing that the dropdown for pagination shows just one option: 50 items per a page](https://user-images.githubusercontent.com/119861/229533850-765e829f-7324-43c6-b71e-1887b7e275dd.png)

![useless machine](https://media.tenor.com/ZHRdOnvwCHgAAAAC/funny.gif)

**Comment by FKolwa** [comment]
Solved in redesign. More specific #117
