### ISSUE TITLE
Going to the last page does nothing for me in Azure

### ISSUE THREAD

**Issue by ondrejbudai** [redhatcloudx/cloud-image-directory-frontend#70]
Reproducer:

1) Go to the Azure list
2) Go to the last page

After these steps, nothing happens. The Javascript console shows not very helpful:

```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by FKolwa** [comment]
It seems that this issue has been fixed. @major @miyunari can any of you reproduce this behavior?

**Comment by major** [comment]
This seems to work for me now.

**Comment by FKolwa** [comment]
Solved in redesign. More specific #117
