### ISSUE TITLE
`cursor: pointer` in the top menu is used in unclickable areas

### ISSUE THREAD

**Issue by ondrejbudai** [redhatcloudx/cloud-image-directory-frontend#73]
If you click directly on the text "AWS", you get to the AWS page. However, if you click a few pixels from the text, you can still see `cursor: pointer`, but actually clicking in this area does nothing.

Examples:
![image](https://user-images.githubusercontent.com/119861/229539912-f3c43760-2bcb-4d9f-9792-ed3fc77105f2.png)
Clicking works just fine.

![image](https://user-images.githubusercontent.com/119861/229539840-d85b4fbb-a0fb-4f41-8541-4de1eff4aa4c.png)
Clicking does nothing.

**Comment by FKolwa** [comment]
Solved in redesign. More specific #100 and #92
