### ISSUE TITLE
missing a way to copy links to a specific image

### ISSUE THREAD

**Issue by frzifus** [redhatcloudx/cloud-image-directory-frontend#82]
It seems that it is not possible to send links to individual images. Currently there is only this list view. It would be nice to have a share button or a detail link that serves the [image data](https://imagedirectory.cloud/images/v1/google/global/rhel_7_x86_64) via a frontend view - e.g.: `https://imagedirectory.cloud/browser/GCP/global/rhel_7_x86_64`

See: https://github.com/redhatcloudx/cloud-image-directory-frontend/pull/81

<details>
<summary>
Current image detail view
</summary>

![grafik](https://user-images.githubusercontent.com/10403402/231389211-ca4c5418-9b0d-4e81-b613-c4d27c2b2a09.png)

</details>

**Comment by FKolwa** [comment]
solved in #81
